---
spring:
  cloud:
    config:
      uri: http://localhost:8888    
  boot:
    admin:
      url: http://localhost:8762
eureka: 
  client: 
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
