info: 服务自动发现
server:
  port: 8761
spring:
  application:
    name: 服务发现
  boot:
    admin:
      url: http://localhost:8762
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/