---
server:
  port: 8761
spring:
  boot:
    admin:
      url: http://localhost:8762
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/         